config/routes.rb
Rails.application.routes.draw do
  get 'people/index'

  get 'people/autocomplete_person_name'

  get 'people/autocomplete_person_name_sql'

  root :to => 'people#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  after_save :load_into_soulmate

  def load_into_soulmate
    loader = Soulmate::Loader.new("person")
    loader.add("term" => name, "id" => id, "score" => rating_count)
  end

  def self.search(term)
    matches = Soulmate::Matcher.new('person').matches_for_term(term, :limit => 50)
    matches.collect {|match| {"id" => match["id"], "label" => match["term"], "value" => match["term"] } }
  end

  def self.searchsql(term)
  	matches = self.find_by_sql("Select * from people where name like '#{term}%' order by rating_count limit 50")
  	matches.collect {|match| {"id" => match["id"], "label" => match["term"], "value" => match["name"] } }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
  end

  def autocomplete_person_name
    render :json => Person.search(params['term'])
  end

  def autocomplete_person_name_sql
    render :json => Person.searchsql(params['term'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoulmateExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div style="width: 100%; height: 100px; text-align: center;">
	<img src="/assets/logo.png" alt="fiverr" style="height: inherit;"/>
</div>
<%= yield %>

</body>
</html>

app/views/people/autocomplete_person_name.html.erb
<%= text_field_tag 'person_name' %>

<script>
$(function() {
  $("#person_name" ).autocomplete({
    source: "<%= people_autocomplete_person_name_path %>"
  });
})
</script>

app/views/people/index.html.erb
<div style="text-align: center;">
With Redis: <%= text_field_tag 'person_name' %>
With SQL: <%= text_field_tag 'person_name_sql' %>
</div>
<script>
$(function() {
  $("#person_name").autocomplete({
    source: "<%= people_autocomplete_person_name_path %>"
  });
  $("#person_name_sql").autocomplete({
    source: "<%= people_autocomplete_person_name_sql_path %>"
  });
})
</script>